export const INTRODUCE_DATA = [
  {
    id: 1,
    title: "",
    src: "https://help.nflxext.com/43e0db2f-fea0-4308-bfb9-09f2a88f6ee4_what_is_netflix_1_en.png",
    p1: "The Movie Database is a subscription-based streaming service that allows our members to watch TV shows and movies without commercials on an internet-connected device.",
    p2: "You can also download TV shows and movies to your iOS, Android, or Windows 10 device and watch without an internet connection.",
    p3: "If you're already a member and would like to learn more about using The Movie Database, visit Getting started with The Movie Database.",
    p4: "",
    p5: "",
    p6: "",
  },
  {
    id: 2,
    title: "TV Shows & Movies",
    src: "https://help.nflxext.com/396a2a39-8d34-4260-b07a-6391fe04ded5_what_is_netflix_2_en.png",
    p1: "The Movie Database content varies by region and may change over time. You can watch from a wide variety of award-winning The Movie Database Originals, TV shows, movies, documentaries, and more.",
    p2: "The more you watch, the better The Movie Database gets at recommending TV shows and movies we think you'll enjoy.",
    p3: "",
    p4: "",
    p5: "",
    p6: "",
  },
  {
    id: 3,
    title: "Supported Devices",
    src: "https://help.nflxext.com/7ac9b493-ae69-431a-923d-3cb8a79d7e63_what_is_netflix_3_en.png",
    p1: "You can watch The Movie Database through any internet-connected device that offers the The Movie Database app, including smart TVs, game consoles, streaming media players, set-top boxes, smartphones, and tablets. You can also watch The Movie Database on your computer using an internet browser. You can review the  system requirements for web browser compatibility, and check our internet speed recommendations to achieve the best performance.",
    p2: "Need help getting set up? Search our Help Center for the manufacturer of the device you're using.",
    p3: "NOTE: The The Movie Database app may come pre-loaded on certain devices, or you may need to download the The Movie Database app onto your device. The Movie Database app functionality may differ between devices.",
    p4: "",
    p5: "",
    p6: "",
  },
  {
    id: 4,
    title: "Plans and Pricing",
    src: "https://help.nflxext.com/b3e9e3a3-20ff-4974-87d4-162e0a547768_what_is_netflix_4_en.png",
    p1: "Each The Movie Database plan determines the number of devices you can watch The Movie Database on at the same time and if you prefer to view in Standard Definition (SD), High Definition (HD), or Ultra High Definition (UHD).",
    p2: "Compare our plans and pricing to decide which one is right for you. You can easily change your plan or cancel online at any time.",
    p3: "",
    p4: "",
    p5: "",
    p6: "",
  },
  {
    id: 5,
    title: "Get Started!",
    src: "https://help.nflxext.com/0af6ce3e-b27a-4722-a5f0-e32af4df3045_what_is_netflix_5_en.png",
    p1: "Follow these easy steps to start watching The Movie Database today:",
    p2: "1. Visit the-movie-database-sangnlh.vercel.app/.",
    p3: "2. Choose the plan that's right for you.",
    p4: "3. Create an account by entering your email address and creating a password.",
    p5: "4. Enter a payment method. As a The Movie Database member, you are charged once a month on the date you signed up.",
    p6: "That's it. Enjoy The Movie Database!",
  },
];
